application:
  title: SnowCamp Call for paper
  url: https://cfp.snowcamp.io
  email: contact@openconf.com
  eventurl: http://snowcamp.io
  enddate: Oct. 14th, 2016
  show_submission_count: false
  airport: LYS
  arrival: 2014-10-26
  departure: 2014-10-31
  secure_ssl: true

api:
  enabled: true

cache:
  enabled: false

database:
  host: 127.0.0.1
  database: cfp
  dsn: mysql:dbname=cfp;host=127.0.0.1
  user: root
  password: %datatbase_password%

mail:
  host: ~
  port: ~
  username: ~
  password: ~
  encryption: ~
  auth_mode: ~
